version: '3'
services:
  rabbitmq: # Chama a imagem do RabbitMQ
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Porta para comunicação AMQP
      - "15672:15672" # Porta para a interface administrativa